### ISSUE TITLE
Can I use this on a Mac

### ISSUE THREAD

**Issue by dancomanlive** [Purik/android-studio-docker#1]
If so what is the workflow to get it working. Thanks!

**Comment by PavelMinenkov** [comment]
I'm not sure it will works on Mac cause of Xorg dependency for running  GUI remotely

**Comment by dancomanlive** [comment]
Thanks for the reply. I ll give it a try but what are the steps necessary to (try to) get it working?

**Comment by PavelMinenkov** [comment]
Try this application https://www.xquartz.org/

**Comment by dancomanlive** [comment]
Ok, I installed xquartz, now what do I do?

**Comment by PavelMinenkov** [comment]
Try run docker container by run.sh (see in repo)

**Comment by PavelMinenkov** [comment]
Hello, are you ok?
