### ISSUE TITLE
persist config & downloaded tools to volume

### ISSUE THREAD

**Issue by nalbion** [Purik/android-studio-docker#2]
Thanks for the work on this docker image, for some reason I can't get Android Studio to run on my Linux box - I've spent a day stuck on the "Downloading Components" screen, and this lets me by-pass that.

Which directories do I need to persist to volumes in order to avoid having to reconfigure, download & install the Android SDK and build tools?

If I mount the volumes `~/Android/Sdk` and `~/src`:
```bash
#!/usr/bin/env bash
docker run -it --net=host --env="DISPLAY" \
  -v /tmp/.X11-unix:/tmp/.X11-unix -v "$HOME/.Xauthority:/root/.Xauthority:rw" \
  -v "$HOME/Android/Sdk:/root/Android/Sdk" -v "$HOME/workspace/src:/root/src" \
   purik/android-studio:latest /opt/android-studio/bin/studio.sh
```

:x: I still get asked to import settings
:x: asked to Send usage statistics to Google
:heavy_check_mark: I no longer need to download components
:x: ...but the Android Studio Setup Wizard stops to tell me everything is up to date.
:heavy_check_mark: my project code is still available
:x: ...but the Build/Sync tab still takes a while to download `gradle-5.1.1-all.zip` and run the build

**Comment by nalbion** [comment]
The `AVD` UI warns that `/dev/kvm` is not found.

> Enable VT-x in your BIOS security settings, ensure that your Linux distro has working KVM module

**Comment by nalbion** [comment]
My latest script change fixes all of the issues above.

```bash
#!/usr/bin/env bash
adb kill-server
docker run -it --net=host --env="DISPLAY" \
  --privileged -v /dev/bus/usb:/dev/bus/usb \
  -v /tmp/.X11-unix:/tmp/.X11-unix -v "$HOME/.Xauthority:/root/.Xauthority:rw" \
  -v "$HOME/Android/Sdk:/root/Android/Sdk" -v "$HOME/.AndroidStudio3.4:/root/.AndroidStudio3.4" \
  -v "$HOME/workspace/src:/root/src" \
   purik/android-studio:latest /opt/android-studio/bin/studio.sh
```

:heavy_check_mark: I don't get asked to import settings
:heavy_check_mark: I don't get asked to Send usage statistics to Google
:heavy_check_mark: I no longer need to download components
:heavy_check_mark: I don't see Android Studio Setup Wizard at all
heavy_check_mark my project code is still available after restart
:heavy_check_mark: the Build/Sync tab no longer downloads `gradle-5.1.1-all.zip` , it just runs the build
:heavy_check_mark: Debugging works on virtual and physical devices - it even remembers the config

**Comment by PavelMinenkov** [comment]
Sorry for too late answer. 
IS it necessarily for you to persist volumes? I prefer to commit docker image and run every time commited image as need.

**Comment by nalbion** [comment]
I'm using this docker container because I couldn't get Android Studio running on my Linux box directly.

I might be able to use `docker commit` as you say - but to be honest I've never heard of it :-)

An example in your readme would save me from having to RTFM ;-)

**Comment by PavelMinenkov** [comment]
Done: https://github.com/Purik/android-studio-docker/blob/master/README.md#persist-data-and-volumes

**Comment by nalbion** [comment]
Do you then edit the `docker run` command in `run.sh` to reference the new image `my_studio_image_name`, or si that _the_ image for `purik/android-studio:latest` on my computer now?

Even with the changes I've made in this PR, I still need to generate a new debug key and upload that for my "Sign in with Google" button. Maybe I need to read more about `docker commit`

**Comment by PavelMinenkov** [comment]
I have updated ```run.sh``` script that make it more easy prepare your image
